
replicas: 1
registryUrl: https://hub.docker.com/repositories/tigerwk
builder_ns: tigerwk
builder_ns_test: ghcr.io/open-rmf/rmf_deployment_template
hostName: rmf.tfk3s.ezey.link

global:
  ROS_DOMAIN_ID: 15
  DDS_CONFIG_MOUNTPATH: /etc/cyclonedds
  DDS_CONFIG_VOLUME: cyclonedds-configmap
  DDS_ENV: CYCLONEDDS_URI
  DDS_CONFIG: /etc/cyclonedds/cyclonedds.xml
  RMW_IMPLEMENTATION: rmw_cyclonedds_cpp

  RMF_USE_SIM_TIME: "false"
  RMF_BIDDING_TIME_WINDOW: "2.0"
  RMF_TRAJECTORY_VISUALIZER_LEVEL_NAME: "L1"
  RMF_BUILDING_MAP_SERVER_CONFIG_PATH: "/opt/rmf/install/mysite_maps/share/mysite_maps/office/office.building.yaml"
  RMF_FAILOVER_MODE: "false"
  RMF_SERVER_URI: "ws://localhost:8000/_internal"
  # REACT_APP_TRAJECTORY_SERVER: https://rmf.tfk3s.ezey.link/trajectory
  # REACT_APP_RMF_SERVER: https://rmf.tfk3s.ezey.link/rmf/api/v1
  # REACT_APP_KEYCLOAK_CONFIG: {"realm": "rmf-web", "clientId": "dashboard", "url": "https://rmf.tfk3s.ezey.link/auth"}
