---
apiVersion: v1
kind: Pod
namespace: 
metadata:
  name: rmf-building-map-server
spec:
  restartPolicy: Always
  hostNetwork: true
  containers:
    - name: rmf-building-map-server
      image: {{ .Values.builder_ns }}/rmf-site
      imagePullPolicy: Always
      env:
        - name: {{ .Values.global.DDS_ENV | quote }}
          value: {{ .Values.global.DDS_CONFIG | quote }}
        - name: ROS_DOMAIN_ID
          value: {{ .Values.global.ROS_DOMAIN_ID | quote }}
        - name: RMW_IMPLEMENTATION
          value: {{ .Values.global.RMW_IMPLEMENTATION | quote }}
        - name: RMF_BUILDING_MAP_SERVER_CONFIG_PATH
          value: {{ .Values.global.RMF_BUILDING_MAP_SERVER_CONFIG_PATH | quote }}
      command: ["/bin/bash"]
      args: 
        - -c
        - >
          /ros_entrypoint.sh
          ros2 run rmf_building_map_tools building_map_server
          $(RMF_BUILDING_MAP_SERVER_CONFIG_PATH)
      volumeMounts:
        - mountPath: {{ .Values.global.DDS_CONFIG_MOUNTPATH | quote }}
          name: {{ .Values.global.DDS_CONFIG_VOLUME | quote }}
  volumes:
    - name: {{ .Values.global.DDS_CONFIG_VOLUME | quote }}
      configMap:
        name: {{ .Values.global.DDS_CONFIG_VOLUME | quote }}

---

apiVersion: v1
kind: Pod
metadata:
  name: fleet-adapter
spec:
  restartPolicy: Always
  hostNetwork: true
  containers:
    - name: fleet-adapter
      image: {{ .Values.builder_ns }}/fleet_adapter_mir
      imagePullPolicy: Always
      env:
        - name: CONFIG_FILE
          value: {{ .Values.global.CONFIG_FILE | quote }}
        - name: NAV_GRAPH_FILE
          value: {{ .Values.global.NAV_GRAPH_FILE | quote }}
        - name: SERVER_URI
          value: {{ .Values.global.RMF_SERVER_URI | quote }}
        - name: RMF_USE_SIM_TIME
          value: {{ .Values.global.RMF_USE_SIM_TIME | quote }}
        - name: {{ .Values.global.DDS_ENV | quote }}
          value: {{ .Values.global.DDS_CONFIG | quote }}
        - name: ROS_DOMAIN_ID
          value: {{ .Values.global.ROS_DOMAIN_ID | quote }}
        - name: RMW_IMPLEMENTATION
          value: {{ .Values.global.RMW_IMPLEMENTATION | quote }}
      command: ["/bin/bash"]
      args: 
        - -c
        - >
          /ros_entrypoint.sh 
          ros2 run fleet_adapter_mir fleet_adapter_mir use_sim_time:=false nav_graph_file:=$(NAV_GRAPH_FILE) config_file:=$(CONFIG_FILE)
      volumeMounts:
        - mountPath: {{ .Values.global.DDS_CONFIG_MOUNTPATH | quote }}
          name: {{ .Values.global.DDS_CONFIG_VOLUME | quote }}
        - mountPath: {{ .Values.global.NAV_GRAPH_FILE | quote }}
          name: nav-graph-file
        - mountPath: {{ .Values.global.CONFIG_FILE | quote }}
          name: config-file
  volumes:
    - name: {{ .Values.global.DDS_CONFIG_VOLUME | quote }}
      configMap:
        name: {{ .Values.global.DDS_CONFIG_VOLUME | quote }}
        
    - name: nav-graph-file
      configMap:
        name: nav-graph-configmap-name

    - name: config-file
      configMap:
        name: config-file-configmap-name

# Any site specific fleet adapters may be added here
